### ISSUE TITLE
input does not match any value of interface

### ISSUE THREAD

**Issue by alexanderek** [IgorKha/wireguard-mikrotik#2]
In the client config for Mikrotik (RSC), there is no interface (wg0, etc.), you need to add: 
`/interface wireguard add name=wg0`

**Comment by IgorKha** [comment]
this param exist in the client config for Mikrotik (RSC)
https://github.com/IgorKha/wireguard-mikrotik/blob/e095ae31de77a706538c33bfa69ef52a5a70c607/wireguard-mikrotik.sh#L274
![Screenshot_20221202_094224](https://user-images.githubusercontent.com/2268209/205217175-0de62da2-3fa7-45ad-8064-543cc8df9f5e.png)

**Comment by IgorKha** [comment]
the user configuration file should not contain interface settings, for this there is another file 
`./wireguard/<interface name>/mikrotik/<interface name>.rsc`
https://github.com/IgorKha/wireguard-mikrotik/blob/e095ae31de77a706538c33bfa69ef52a5a70c607/wireguard-mikrotik.sh#L171
